export type RosterPlayer = {
  id: string;
  firstName: string;
  lastName: string;
  position: string;
  jerseyNumber: string;
  reference: string;
  label: string;
  reason: string;
};

export const SPURS_ROSTER: RosterPlayer[] = [
  {
    id: 'wemby',
    firstName: 'Victor',
    lastName: 'Wembanyama',
    position: 'C',
    jerseyNumber: '1',
    reference: '1641705',
    label: 'Wembanyama',
    reason: 'Blocks, milestones, and postgame clips',
  },
  {
    id: 'fox',
    firstName: "De'Aaron",
    lastName: 'Fox',
    position: 'G',
    jerseyNumber: '4',
    reference: '1628368',
    label: 'Fox',
    reason: 'Lead guard pace and clutch-time alerts',
  },
  {
    id: 'castle',
    firstName: 'Stephon',
    lastName: 'Castle',
    position: 'G',
    jerseyNumber: '5',
    reference: '1642264',
    label: 'Castle',
    reason: 'Starting lineup and assist leader alerts',
  },
  {
    id: 'harper',
    firstName: 'Dylan',
    lastName: 'Harper',
    position: 'G',
    jerseyNumber: '2',
    reference: '1642844',
    label: 'Harper',
    reason: 'Backcourt minutes and rookie milestone alerts',
  },
  {
    id: 'mclaughlin',
    firstName: 'Jordan',
    lastName: 'McLaughlin',
    position: 'G',
    jerseyNumber: '0',
    reference: '1629162',
    label: 'McLaughlin',
    reason: 'Second-unit ballhandling and rotation updates',
  },
  {
    id: 'vassell',
    firstName: 'Devin',
    lastName: 'Vassell',
    position: 'G',
    jerseyNumber: '24',
    reference: '1630170',
    label: 'Vassell',
    reason: 'Three-point streaks and scoring runs',
  },
  {
    id: 'keldon',
    firstName: 'Keldon',
    lastName: 'Johnson',
    position: 'F',
    jerseyNumber: '3',
    reference: '1629640',
    label: 'Johnson',
    reason: 'Bench scoring and scoring bursts',
  },
  {
    id: 'sochan',
    firstName: 'Jeremy',
    lastName: 'Sochan',
    position: 'F',
    jerseyNumber: '10',
    reference: '1631110',
    label: 'Sochan',
    reason: 'Defensive stops and energy plays',
  },
  {
    id: 'champagnie',
    firstName: 'Julian',
    lastName: 'Champagnie',
    position: 'F',
    jerseyNumber: '30',
    reference: '1630577',
    label: 'Champagnie',
    reason: 'Catch-and-shoot threes and wing minutes',
  },
  {
    id: 'barnes',
    firstName: 'Harrison',
    lastName: 'Barnes',
    position: 'F',
    jerseyNumber: '40',
    reference: '203084',
    label: 'Barnes',
    reason: 'Veteran scoring and closing lineups',
  },
  {
    id: 'olynyk',
    firstName: 'Kelly',
    lastName: 'Olynyk',
    position: 'F-C',
    jerseyNumber: '8',
    reference: '203482',
    label: 'Olynyk',
    reason: 'Frontcourt spacing and reserve minutes',
  },
  {
    id: 'kornet',
    firstName: 'Luke',
    lastName: 'Kornet',
    position: 'C',
    jerseyNumber: '7',
    reference: '1628436',
    label: 'Kornet',
    reason: 'Rim protection and rotation updates',
  },
  {
    id: 'biyombo',
    firstName: 'Bismack',
    lastName: 'Biyombo',
    position: 'C',
    jerseyNumber: '18',
    reference: '202687',
    label: 'Biyombo',
    reason: 'Interior defense and board protection',
  },
  {
    id: 'bryant',
    firstName: 'Carter',
    lastName: 'Bryant',
    position: 'F',
    jerseyNumber: '11',
    reference: '1642868',
    label: 'Bryant',
    reason: 'Development minutes and upside alerts',
  },
  {
    id: 'miller',
    firstName: 'Emanuel',
    lastName: 'Miller',
    position: 'F',
    jerseyNumber: '14',
    reference: '1641801',
    label: 'Miller',
    reason: 'Two-way forward tracking and call-up alerts',
  },
  {
    id: 'jones-garcia',
    firstName: 'David',
    lastName: 'Jones Garcia',
    position: 'G-F',
    jerseyNumber: '25',
    reference: '1642357',
    label: 'Jones Garcia',
    reason: 'Two-way scoring bursts and depth updates',
  },
  {
    id: 'waters',
    firstName: 'Lindy',
    lastName: 'Waters III',
    position: 'G',
    jerseyNumber: '43',
    reference: '1630322',
    label: 'Waters III',
    reason: 'Bench shooting and rotational spacing',
  },
  {
    id: 'plumlee',
    firstName: 'Mason',
    lastName: 'Plumlee',
    position: 'C',
    jerseyNumber: '45',
    reference: '203486',
    label: 'Plumlee',
    reason: 'Backup center minutes and rim runs',
  },
  {
    id: 'ingram',
    firstName: 'Harrison',
    lastName: 'Ingram',
    position: 'F',
    jerseyNumber: '55',
    reference: '1631127',
    label: 'Ingram',
    reason: 'Two-way wing development updates',
  },
];
